// render and parse the canonical TokenSet shape: emits both the runtime
// tokens.ts (single- or multi-mode) and the .divebar.json sidecar that the
// lint/sync pipeline reads back

import type { TokenSet } from './types';
import { TokenSetSchema } from './schema';

// render a token set to typescript code (single-mode or multi-mode)
export function renderTokens(ts: TokenSet): string {
  if (ts.modes && ts.modes.length > 0) {
    return renderMultiModeTokens(ts);
  }
  return renderSingleModeTokens(ts);
}

// emit a flat `export const tokens = { ... }` for single-mode sets
function renderSingleModeTokens(ts: TokenSet): string {
  const flat = flattenTokenValues(ts.tokens);
  return [
    `// generated by divebar`,
    `export const tokens = ${JSON.stringify(flat, null, 2)} as const;`,
    ``,
  ].join('\n');
}

// emit `export const tokensByMode = { light: {...}, dark: {...} }` for multi-mode sets
// also emits `modeIdByName` so consumers can look up a figma modeId from the
// friendly mode name without losing either piece of information
function renderMultiModeTokens(ts: TokenSet): string {
  const modes = ts.modes!;
  const modeData: Record<string, Record<string, any>> = {};
  const modeIdByName: Record<string, string> = {};

  for (const mode of modes) {
    modeData[mode.folder] = flattenForMode(ts.tokens, mode.id);
    modeIdByName[mode.name] = mode.id;
  }

  return [
    `// generated by divebar`,
    `export const tokensByMode = ${JSON.stringify(modeData, null, 2)} as const;`,
    `export type ThemeMode = keyof typeof tokensByMode;`,
    `export const modeIdByName = ${JSON.stringify(modeIdByName, null, 2)} as const;`,
    ``,
  ].join('\n');
}

// extract resolved values from a token tree, collapsing aliases
function flattenTokenValues(tokens: any, prefix = ''): any {
  const out: Record<string, any> = {};

  for (const [key, val] of Object.entries(tokens)) {
    const v = val as any;

    if (v && typeof v === 'object' && '$type' in v) {
      if (v.$value !== undefined) {
        const resolved =
          typeof v.$value === 'object' && '$alias' in v.$value
            ? v.$value.$alias
            : v.$value;
        out[key] = resolved;
      }
    } else if (v && typeof v === 'object') {
      out[key] = flattenTokenValues(v);
    }
  }

  return out;
}

// extract values for a specific mode, falling back to the first available mode
function flattenForMode(tokens: any, mode: string): Record<string, any> {
  const out: Record<string, any> = {};

  for (const [key, val] of Object.entries(tokens)) {
    const v = val as any;

    if (v && typeof v === 'object' && '$type' in v) {
      if (v.$valuesByMode) {
        const fallbackKey = Object.keys(v.$valuesByMode)[0] as string;
        const raw = v.$valuesByMode[mode] ?? v.$valuesByMode[fallbackKey];
        out[key] =
          typeof raw === 'object' && raw && '$alias' in raw ? raw.$alias : raw;
      } else if (v.$value !== undefined) {
        out[key] =
          typeof v.$value === 'object' && '$alias' in v.$value
            ? v.$value.$alias
            : v.$value;
      }
    } else if (v && typeof v === 'object') {
      out[key] = flattenForMode(v, mode);
    }
  }

  return out;
}

// write the canonical .divebar.json for round-trip token storage
// strips $schema from output so divebar never emits the dead pointer URL
export function renderTokensSpec(ts: TokenSet): string {
  const { $schema: _schema, ...rest } = ts;
  return JSON.stringify(rest, null, 2) + '\n';
}

// read a .divebar.json back into a validated token set
export function parseTokensSpec(json: string): TokenSet {
  return TokenSetSchema.parse(JSON.parse(json)) as unknown as TokenSet;
}
